---
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: rabbit
      name: rabbit
    spec:
      ports:
      - name: rabbit
        port: 5672
        protocol: TCP
        targetPort: 5672
      selector:
        app: rabbit
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: rabbit
      name: rabbit
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: rabbit
      template:
        metadata:
          labels:
            app: rabbit
        spec:
          containers:
          - name: rabbit
            image: rabbitmq
            env:
              - name: RABBITMQ_PASS
                value: "password"
            resources:
              limits:
                memory: 512Mi
                cpu: 500m
              requests:
                cpu: 50m
                memory: 128Mi
            # terminationMessagePath: /dev/termination-log
            # terminationMessagePolicy: File
